# -*- coding: utf-8 -*-
"""question1DL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15xY3rPSURsasOwxmPrrYvwmG_6ZPvtbz
"""

!pip install wandb -qU
import numpy as np

#!pip install wandb

import wandb
import os
from keras.datasets import fashion_mnist
os.environ['WAND_NOTEBOOK_NAME']='question1DL'

!wandb login 44fa96b263794ea519fb29399eb6b8f469eb934b

wandb.init(project='DLassignment1',entity='singhbhavesh999',name='question1DL')
label_map = {0: 'T-Shirt', 1: 'Trouser', 2: 'Pullover', 3: 'Dress', 4: 'Coat',
              5: 'Sandal', 6: 'Shirt', 7: 'Sneaker', 8: 'Bag', 9: 'Ankle Boot'}

(train_X,train_Y),(test_X,test_Y)=fashion_mnist.load_data()
train_len=train_X.shape[0]
collected_items=[]
item_labels=[]
for i in range(train_len):
  if(label_map[train_Y[i]] not in item_labels):
    collected_items.append(train_X[i])
    item_labels.append(label_map[train_Y[i]])
  if (len(item_labels)==10):
    break


wandb.log({"Question 1 Images": [wandb.Image(img, caption=lbl) for img,lbl in zip(collected_items,item_labels)]})
