# -*- coding: utf-8 -*-
"""DLquestion1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16L7I8bHZKDaTVqm-QW81O3wy5Zjk4z_Z
"""

from keras.datasets import fashion_mnist
from matplotlib import pyplot as plt
(train_X,train_Y),(test_X,test_Y)=fashion_mnist.load_data()

label_map = {0: 'T-Shirt', 1: 'Trouser', 2: 'Pullover', 3: 'Dress', 4: 'Coat',
              5: 'Sandal', 6: 'Shirt', 7: 'Sneaker', 8: 'Bag', 9: 'Ankle Boot'}

train_len=train_X.shape[0]
collected_items=[]
item_labels=[]
for i in range(train_len):
  if(train_Y[i] not in item_labels):
    collected_items.append(train_X[i])
    item_labels.append(train_Y[i])
  if (len(item_labels)==10):
    break

plt.figure(figsize=(7,7))
for i in range(10):
  plt.subplot(3,4,i+1)
  plt.imshow(collected_items[i],cmap=plt.get_cmap('gray'),aspect=1.5)
  plt.tight_layout()    # to adjust space between the subplots 
  plt.xticks(())  
  plt.yticks(())
  plt.title(label_map[item_labels[i]])    # to add title to the subplots
